// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package room

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/Megidy/k/static/templates/components"

func LoadCreationOfRoom() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><script src=\"https://unpkg.com/htmx.org@1.9.2\"></script><title>Create Room</title><link rel=\"stylesheet\" href=\"/static/css/room/roomCreation.css\"></head><body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.TopNavBar().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"roomCreationWrapper\"><div class=\"room\"><form hx-post=\"/room/create/confirm\"><div class=\"form-group\"><label for=\"code\">number of players</label> <input type=\"number\" id=\"players\" name=\"players\" min=\"1\" max=\"50\" placeholder=\"1-50 players \" required></div><div class=\"form-group\"><label for=\"questions\">number of questions</label> <input type=\"number\" id=\"questions\" name=\"questions\" min=\"5\" max=\"20\" placeholder=\"5-20 questions\" required></div><div class=\"form-group\"><label>What would you like to do?</label> <input type=\"radio\" id=\"play\" name=\"type\" value=\"I want to play\" required> <label for=\"play\">play</label><br><input type=\"radio\" id=\"observe\" name=\"type\" value=\"I want to see what players are doing\" required> <label for=\"observe\">spectate</label></div><button type=\"submit\" class=\"btn\">Confirm</button></form></div></div></body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
