services:
  api:
    restart: always
    depends_on:
      - redis
      - mysql
    env_file:
      - .env
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: ["/api"]
    

  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: k

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  db_data:
