// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func TopNavBar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<head><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><link rel=\"stylesheet\" href=\"/static/css/components/topbar.css\"><link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\"></head><body><ul class=\"topnav\" id=\"myTopnav\"><li class=\"icon\"><a href=\"javascript:void(0);\" class=\"toggle-button\" onclick=\"toggleMenu()\"><i class=\"fa fa-bars\"></i></a></li><li><a href=\"/home\"><i class=\"fa fa-home\"></i> Home</a></li><li><a href=\"/room/connect\"><i class=\"fa fa-plug\"></i> Connect to room</a></li><li><a href=\"/room/create\"><i class=\"fa fa-plus\"></i> Create room</a></li><li><a href=\"/topic/create\"><i class=\"fa fa-pencil\"></i> Create topic</a></li><li><a href=\"/account/info\"><i class=\"fa fa-user\"></i> Account</a></li><li><a href=\"/account/login\"><i class=\"fa-solid fa-arrow-right-to-bracket\">Login</i></a></li></ul><script>\r\n        function toggleMenu() {\r\n    const nav = document.getElementById(\"myTopnav\");\r\n    if (nav.className === \"topnav\") {\r\n        nav.className += \" responsive\"; \r\n    } else {\r\n        nav.className = \"topnav\"; \r\n    }\r\n}\r\n        </script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
